<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('country')->truncate();
        Schema::enableForeignKeyConstraints();

        $countries = [
            ['name' => 'Afganistán', 'code' => 'AF'],
            ['name' => 'Islas Åland', 'code' => 'AX'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Argelia', 'code' => 'DZ'],
            ['name' => 'Samoa Americana', 'code' => 'AS'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguila', 'code' => 'AI'],
            ['name' => 'Antártida', 'code' => 'AQ'],
            ['name' => 'Antigua y Barbuda', 'code' => 'AG'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'Austria', 'code' => 'EN'],
            ['name' => 'Azerbaiyán', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bahréin', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Bielorrusia', 'code' => 'POR'],
            ['name' => 'Bélgica', 'code' => 'BE'],
            ['name' => 'Belice', 'code' => 'BZ'],
            ['name' => 'Benín', 'code' => 'BJ'],
            ['name' => 'Bermudas', 'code' => 'BM'],
            ['name' => 'Bután', 'code' => 'BT'],
            ['name' => 'Bolivia', 'code' => 'BO'],
            ['name' => 'Bonaire, San Eustaquio y Saba', 'code' => 'BQ'],
            ['name' => 'Bosnia y Herzegovina', 'code' => 'BA'],
            ['name' => 'Botsuana', 'code' => 'BW'],
            ['name' => 'Isla Bouvet', 'code' => 'BV'],
            ['name' => 'Brasil', 'code' => 'BR'],
            ['name' => 'Territorio Británico del Océano Índico', 'code' => 'IO'],
            ['name' => 'Brunéi Darussalam', 'code' => 'BN'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Camboya', 'code' => 'KH'],
            ['name' => 'Camerún', 'code' => 'CM'],
            ['name' => 'Canadá', 'code' => 'CA'],
            ['name' => 'Cabo Verde', 'code' => 'CV'],
            ['name' => 'Islas Caimán', 'code' => 'KY'],
            ['name' => 'República Centroafricana', 'code' => 'CF'],
            ['name' => 'Chad', 'code' => 'TD'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Isla de Navidad', 'code' => 'CX'],
            ['name' => 'Islas Cocos (Keeling)', 'code' => 'CC'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comoras', 'code' => 'KM'],
            ['name' => 'Congo', 'code' => 'CG'],
            ['name' => 'República Democrática del Congo', 'code' => 'CD'],
            ['name' => 'Islas Cook', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Costa de Marfil', 'code' => 'CI'],
            ['name' => 'Croacia', 'code' => 'HR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Curazao', 'code' => 'CW'],
            ['name' => 'Chipre', 'code' => 'CY'],
            ['name' => 'República Checa', 'code' => 'CZ'],
            ['name' => 'Dinamarca', 'code' => 'DK'],
            ['name' => 'Yibuti', 'code' => 'DJ'],
            ['name' => 'Dominica', 'code' => 'DM'],
            ['name' => 'República Dominicana', 'code' => 'DO'],
            ['name' => 'Ecuador', 'code' => 'CE'],
            ['name' => 'Egipto', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Guinea Ecuatorial', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Etiopía', 'code' => 'ET'],
            ['name' => 'Islas Malvinas (Falkland Islands)', 'code' => 'FK'],
            ['name' => 'Islas Feroe', 'code' => 'FO'],
            ['name' => 'Fiyi', 'code' => 'FJ'],
            ['name' => 'Finlandia', 'code' => 'FI'],
            ['name' => 'Francia', 'code' => 'FR'],
            ['name' => 'Guayana Francesa', 'code' => 'GF'],
            ['name' => 'Polinesia Francesa', 'code' => 'PF'],
            ['name' => 'Territorios Australes Franceses', 'code' => 'TF'],
            ['name' => 'Gabón', 'code' => 'GA'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Alemania', 'code' => 'DE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Grecia', 'code' => 'GR'],
            ['name' => 'Groenlandia', 'code' => 'GL'],
            ['name' => 'Granada', 'code' => 'GD'],
            ['name' => 'Guadalupe', 'code' => 'GP'],
            ['name' => 'Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guernsey', 'code' => 'GG'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bisáu', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haití', 'code' => 'HT'],
            ['name' => 'Isla Heard y McDonald McDonald', 'code' => 'HM'],
            ['name' => 'Santa Sede (Estado de la Ciudad del Vaticano)', 'code' => 'VA'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Hungría', 'code' => 'HU'],
            ['name' => 'Islandia', 'code' => 'ES'],
            ['name' => 'India', 'code' => 'EN'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Irán', 'code' => 'IR'],
            ['name' => 'Irak', 'code' => 'IQ'],
            ['name' => 'Irlanda', 'code' => 'ES'],
            ['name' => 'Isla de Man', 'code' => 'IM'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Italia', 'code' => 'IT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Japón', 'code' => 'JP'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazajstán', 'code' => 'KZ'],
            ['name' => 'Kenia', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'República Popular Democrática de Corea (Norte)', 'code' => 'KP'],
            ['name' => 'República de Corea (Sur)', 'code' => 'KR'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Kirguistán', 'code' => 'KG'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Letonia', 'code' => 'LV'],
            ['name' => 'Líbano', 'code' => 'LB'],
            ['name' => 'Lesoto', 'code' => 'LS'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Libia', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lituania', 'code' => 'LT'],
            ['name' => 'Luxemburgo', 'code' => 'LU'],
            ['name' => 'Macao', 'code' => 'MO'],
            ['name' => 'Macedonia', 'code' => 'MK'],
            ['name' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malasia', 'code' => 'MI'],
            ['name' => 'Maldivas', 'code' => 'MV'],
            ['name' => 'Malí', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Islas Marshall', 'code' => 'MH'],
            ['name' => 'Martinica', 'code' => 'MQ'],
            ['name' => 'Mauritania', 'code' => 'MR'],
            ['name' => 'Mauricio', 'code' => 'MU'],
            ['name' => 'Mayotte', 'code' => 'YT'],
            ['name' => 'México', 'code' => 'MX'],
            ['name' => 'Micronesia', 'code' => 'FM'],
            ['name' => 'República de Moldavia', 'code' => 'MD'],
            ['name' => 'Mónaco', 'code' => 'MC'],
            ['name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Montenegro', 'code' => 'YO'],
            ['name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Marruecos', 'code' => 'MA'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Países Bajos', 'code' => 'NL'],
            ['name' => 'Nueva Caledonia', 'code' => 'NC'],
            ['name' => 'Nueva Zelanda', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'Níger', 'code' => 'NE'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Isla Norfolk', 'code' => 'NF'],
            ['name' => 'Islas Marianas del Norte', 'code' => 'MP'],
            ['name' => 'Noruega', 'code' => 'NO'],
            ['name' => 'Omán', 'code' => 'OM'],
            ['name' => 'Pakistán', 'code' => 'PK'],
            ['name' => 'Palaos', 'code' => 'PW'],
            ['name' => 'Palestina, Estado de', 'code' => 'PS'],
            ['name' => 'Panamá', 'code' => 'PA'],
            ['name' => 'Papúa Nueva Guinea', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Perú', 'code' => 'PE'],
            ['name' => 'Filipinas', 'code' => 'PH'],
            ['name' => 'Pitcairn', 'code' => 'PN'],
            ['name' => 'Polonia', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Puerto Rico', 'code' => 'PR'],
            ['name' => 'Catar', 'code' => 'Control de calidad'],
            ['name' => 'Reunión', 'code' => 'RE'],
            ['name' => 'Rumanía', 'code' => 'RO'],
            ['name' => 'Rusia', 'code' => 'RU'],
            ['name' => 'Ruanda', 'code' => 'RW'],
            ['name' => 'San Bartolomé', 'code' => 'BL'],
            ['name' => 'Santa Elena, Ascensión y Tristan da Cunha', 'code' => 'SH'],
            ['name' => 'San Cristóbal y Nieves', 'code' => 'KN'],
            ['name' => 'Santa Lucía', 'code' => 'LC'],
            ['name' => 'San Martín (parte francesa)', 'code' => 'MF'],
            ['name' => 'San Pedro y Miquelón', 'code' => 'PM'],
            ['name' => 'San Vicente y las Granadinas', 'code' => 'VC'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tomé y Príncipe', 'code' => 'ST'],
            ['name' => 'Arabia Saudita', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leona', 'code' => 'SL'],
            ['name' => 'Singapur', 'code' => 'SG'],
            ['name' => 'Sint Maarten (parte holandesa)', 'code' => 'SX'],
            ['name' => 'Eslovaquia', 'code' => 'SK'],
            ['name' => 'Eslovenia', 'code' => 'SI'],
            ['name' => 'Islas Salomón', 'code' => 'SB'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'Sudáfrica', 'code' => 'ZA'],
            ['name' => 'Islas Georgias del Sur y Sandwich del Sur', 'code' => 'GS'],
            ['name' => 'Sudán del Sur', 'code' => 'SS'],
            ['name' => 'España', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudán', 'code' => 'SD'],
            ['name' => 'Surinam', 'code' => 'SR'],
            ['name' => 'Svalbard y Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Suazilandia', 'code' => 'SZ'],
            ['name' => 'Suecia', 'code' => 'SE'],
            ['name' => 'Suiza', 'code' => 'CH'],
            ['name' => 'República Árabe Siria', 'code' => 'SY'],
            ['name' => 'Taiwán', 'code' => 'TW'],
            ['name' => 'Tayikistán', 'code' => 'TJ'],
            ['name' => 'Tanzania, República Unida de', 'code' => 'TZ'],
            ['name' => 'Tailandia', 'code' => 'TH'],
            ['name' => 'Timor Oriental', 'code' => 'TL'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'code' => 'PARA'],
            ['name' => 'Trinidad y Tobago', 'code' => 'TT'],
            ['name' => 'Túnez', 'code' => 'TN'],
            ['name' => 'Turquía', 'code' => 'TR'],
            ['name' => 'Turkmenistán', 'code' => 'TM'],
            ['name' => 'Islas Turcas y Caicos', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ucrania', 'code' => 'UA'],
            ['name' => 'Emiratos Árabes Unidos', 'code' => 'AE'],
            ['name' => 'Reino Unido', 'code' => 'GB'],
            ['name' => 'Estados Unidos', 'code' => 'US'],
            ['name' => 'Islas menores alejadas de los Estados Unidos', 'code' => 'UM'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistán', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Venezuela, República Bolivariana de', 'code' => 'VE'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Islas Vírgenes Británicas', 'code' => 'VG'],
            ['name' => 'Islas Vírgenes, EE. UU.', 'code' => 'VI'],
            ['name' => 'Wallis y Futuna', 'code' => 'WF'],
            ['name' => 'Sáhara Occidental', 'code' => 'EH'],
            ['name' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Zimbabue', 'code' => 'ZW'],
        ];

        DB::table('country')->insert($countries);
    }
}
